//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_product
    {
        public int Id { get; set; }
        public int quantity { get; set; }
        public int price { get; set; }
        public int base_Id { get; set; }
        public int product_Id { get; set; }
    
        public virtual @base @base { get; set; }
        public virtual product product { get; set; }
    }
}
