//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopEntities : DbContext
    {
    private static ShopEntities _context;
        public ShopEntities()
            : base("name=ShopEntities")
        {
        }
    public static ShopEntities GetContext()
    {
      if( _context == null)
      {
        _context = new ShopEntities();
      }
      return _context;
    }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@base> bases { get; set; }
        public virtual DbSet<base_product> base_product { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<department_product> department_product { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<shop> shops { get; set; }
    }
}
